### ISSUE TITLE
Error can not input multiple fragment files

### ISSUE THREAD

**Issue by nadiabaig** [MinzhuXie/H-PoPG#10]
Hi, 
I am using H-PoPG tool get the haplotypes.
**I am using the following code:**

java -jar /src/H-PoPG-master/H-PoPGv0.2.0.jar -p 4 -f out.txt -v Chr01.vcf  -d phased_Chr01_cc_hap.txt
here the out.txt file contains multiple fragment files:
**frag_cc_0.txt
frag_cc_1.txt
frag_cc_2.txt
frag_cc_3.txt
frag_cc_4.txt
frag_cc_5.txt**

**Error:**
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at dataStructure.Block.<init>(Block.java:36)
        at main.PolyPlotyping.go(PolyPlotyping.java:220)
        at main.PolyPlotyping.main(PolyPlotyping.java:417)

It works fine when only 1 fragment file is provided.

Looking forward for the answer.
Thanks

**Comment by MinzhuXie** [comment]
Please see the readme:   -f input_SNP_matrix_file_name
The input_SNP_matrix_file should be the file providing the information of the SNP matrix, not the fragment file names. 
The format of the file had been described in the README file.
